name: Scheduled Seed Database

on:
  push:
    branches:
      - master  # default branch name

jobs:
  seed-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Node.js version (adjust as needed)

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Run seed.js
      run: |
        cd backend
        node seed.js
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}  # Using the mongodb secret
